# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Ez2-GcH-6xMHkyB-fwu6GVj5OUB1HBH

Import & Chuẩn bị dữ liệu
"""

import pandas as pd
import numpy as np

import pandas as pd
import numpy as np

ANSWER_KEY = np.array([
    'B','A','D','D','C','B','D','A','C','C',
    'D','B','A','B','A','C','B','D','A','C',
    'A','A','B','D','D'
])

def open_file():
    """Task 1: yêu cầu người dùng nhập tên file + try/except."""
    while True:
        filename = input("Enter a class file to grade (i.e. class1 for class1.txt): ")
        realname = filename + ".txt"

        try:
            df = pd.read_csv(realname, header=None)
            print(f"Successfully opened {realname}")
            return df, realname
        except FileNotFoundError:
            print("File cannot be found.")

"""TASK 1 – Mở file + exception handling"""

filename = input("Enter class file name (e.g., class1): ")
file_path = filename + ".txt"

try:
    with open(file_path, "r") as f:
        lines = f.read().splitlines()
    print(f"Successfully opened {file_path}")
except FileNotFoundError:
    print("File cannot be found.")
    raise SystemExit()

"""TASK 2 – Phân tích dữ liệu & đếm lỗi"""

valid_students = []
invalid_count = 0

print("**** ANALYZING ****")

for line in lines:
    valid, err, sid, answers = validate_row(line)

    if not valid:
        invalid_count += 1
        print(f"Invalid line of data: {err}")
        print(line)
        continue

    valid_students.append((sid, answers))

print("\n**** REPORT ****\n")
print("\n Total valid lines: \n", len(valid_students))
print("\n Total invalid lines: \n", invalid_count)

"""TASK 3 – Chấm điểm & thống kê (mean, median, range, skipped, incorrect)"""

scores = []
skipped_all = []
incorrect_all = []

for sid, answers in valid_students:
    score, skipped, incorrect = score_answers(answers)
    scores.append(score)
    skipped_all.append(skipped)
    incorrect_all.append(incorrect)

scores = np.array(scores)
skipped_all = np.array(skipped_all)
incorrect_all = np.array(incorrect_all)

# Thống kê cơ bản
print("\n Total high scores (>80):\n ", (scores > 80).sum())
print("\n Mean score:\n ", scores.mean())
print("\n Highest score:\n ", scores.max())
print("\n Lowest score:\n ", scores.min())
print("\n Range:\n ", scores.max() - scores.min())
print("\n Median:\n ", np.median(scores))

# Câu bị bỏ qua nhiều
skip_counts = skipped_all.sum(axis=0)
max_skip = skip_counts.max()
most_skipped = [i+1 for i in range(25) if skip_counts[i] == max_skip]
print("\n Most skipped questions: \n ", most_skipped, " (Skipped:", max_skip, ")")

# Câu sai nhiều nhất
incorrect_counts = incorrect_all.sum(axis=0)
max_incorrect = incorrect_counts.max()
most_incorrect = [i+1 for i in range(25) if incorrect_counts[i] == max_incorrect]
print("Most incorrect questions:", most_incorrect, " (Incorrect:", max_incorrect, ")")

"""TASK 4 – Xuất file kết quả"""

output_file = filename + "_grades.txt"

with open(output_file, "w") as f:
    for (sid, answers), score in zip(valid_students, scores):
        f.write(f"{sid},{score}\n")

print(f"\n Grades exported to {output_file}\n ")